version: "3"

services: 
    database:
        image: mysql:5.7
        container_name: mysql
        ports: 
           - 3310:3306
        environment: 
         #   MYSQL_USER: guilherme
         #   MYSQL_DATABASE: potentialcrud
         #   MYSQL_PASSWORD: guilherme
            MYSQL_ROOT_PASSWORD: guilherme

    nginx:
        image: nginx:latest
        container_name: server-nginx
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on: 
            - php
    
    php:
        build: ./docker/php7
        container_name: php
        links:
            - database
        environment:
            - PHP_FPM_ENABLE=1
            - PHP_FPM_SERVER_ADDR=php
            - PHP_FPM_SERVER_PORT=9000
        volumes:
            - ./:/var/www/html